#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: Open-Source Hospital
#+AUTHOR: Andrew M Davis, PhD, Khalif D Ball, MD
#+EMAIL: @reconmaster:matrix.org, @kgreasy:matrix.org
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.13)
#+FILETAGS: 気, ki
Objective: Open-Source Hospital

#+BEGIN_QUOTE
I swear by Apollo Healer, by Asclepius, by Hygieia, by Panacea, and by
all the gods and goddesses, making them my witnesses, that I will
carry out, according to my ability and judgment, this oath and this
indenture.

To hold my teacher in this art equal to my own parents; to make him
partner in my livelihood; when he is in need of money to share mine
with him; to consider his family as my own brothers, and to teach them
this art, if they want to learn it, without fee or indenture; to
impart precept, oral instruction, and all other instruction to my own
sons, the sons of my teacher, and to indentured pupils who have taken
the Healer's oath, but to nobody else.

I will use those dietary regimens which will benefit my patients
according to my greatest ability and judgment, and I will do no harm
or injustice to them. Neither will I administer a poison to anybody
when asked to do so, nor will I suggest such a course. Similarly I
will not give to a woman a pessary to cause abortion. But I will keep
pure and holy both my life and my art. I will not use the knife, not
even, verily, on sufferers from stone, but I will give place to such
as are craftsmen therein.

Into whatsoever houses I enter, I will enter to help the sick, and I
will abstain from all intentional wrong-doing and harm, especially
from abusing the bodies of man or woman, bond or free. And whatsoever
I shall see or hear in the course of my profession, as well as outside
my profession in my intercourse with men, if it be what should not be
published abroad, I will never divulge, holding such things to be holy
secrets.

Now if I carry out this oath, and break it not, may I gain for ever
reputation among all men for my life and for my art; but if I break it
and forswear myself, may the opposite befall me.

Hippocrates 先生 - Translation by W.H.S. Jones
#+END_QUOTE
* TODO Introduction
Goal is to raise the ability to provided community funded health-care.
:LOGBOOK:
CLOCK: [2025-06-26 Thu 17:29]
:END:
** TODO [#A] Emergency room- from first aid to life saving measures
** TODO [#B] ICU-critical care needing vents, pumps, machines to stabilize critically ill patients
** TODO [#B] Surgery ward- emergency to trauma surgery
** TODO [#A] Admitting floor- any patients that need monitoring or cannot be discharged due to vitals will be admitted
** TODO [#C] pharmacy-inhouse and discharge medications
** TODO [#B] psychiatric hospitals
